name: Yaml
on: [push]
jobs:
  run:
    name: Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-compiler: [ '4.12.0', '4.10.2', '4.06.2', '4.05.1']
    steps:
    - uses: actions/checkout@master
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin add yaml.dev -n .
    - run: opam pin add yaml-sexp.dev -n .
    - name: Packages
      run: opam depext -yt yaml yaml-sexp
    - name: Dependencies
      run: opam install -t . --deps-only
    - name: Build
      run: opam exec -- dune build
    - name: Test
      run: opam exec -- dune runtest
